const characters = ['Harry', 'Hermione', 'Ron', 'Draco', 'Luna'];
for (let i = 0; i < characters.length; i++) {
    console.log(characters[i]);
}
const firstName = 'Harry';
const house = 'Gryffindor';
console.log(`Welcome, ${firstName} of ${house}!`);
let characterName = 'Hermione';
console.log(characterName.toLowerCase());
console.log(characterName.toUpperCase());
const spell = ' Expelliarmus ';
console.log(spell.trim());
const quote = 'I solemnly swear that I am up to no good';
console.log(quote.slice(11, 16));
const firstName1 = 'Ron';
const lastName = 'Weasley';
console.log(firstName1.concat(' ', lastName));
let sentence = 'Draco is a good wizard';
console.log(sentence.replace('good', 'bad'));
let houses = ['Gryffindor', 'Hufflepuff', 'Ravenclaw'];
houses.push('Slytherin');
houses.pop();
console.log(houses);
let spells = ['Alohomora', 'Lumos', 'Nox'];
spells.unshift('Accio');
spells.shift();
console.log(spells);
const professors = ['Dumbledore', 'McGonagall', 'Snape', 'Hagrid'];
const selectedProfessors = professors.slice(1, 3);
console.log(selectedProfessors);
let students = ['Neville', 'Seamus', 'Dean', 'Parvati'];
students.splice(1, 2);
console.log(students);
let phrase = ' Mischief Managed ';
console.log(phrase.trim().toLowerCase().concat(' - Harry'));
let wizards = ['Harry', 'Hermione', 'Ron'];
wizards.push('Luna', 'Draco');
console.log(wizards);
let message = 'Welcome to Hogwarts School of Witchcraft and Wizardry';
const extracted = message.slice(11, 19).concat(' Castle');
console.log(extracted);
